language: java
sudo: required

jdk:
  - oraclejdk8

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - PGPORT=5432
    - PGHOST=localhost

before_install:
  - chmod +x mvnw
  - sudo service postgresql restart
  - sleep 1

before_script:
  - sudo psql -c "CREATE DATABASE codenames_test;" -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'password'"

script:
  - mvn clean install coveralls:report -B

after_script:
  - echo "Script finished"

after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"

after_failure:
  - echo "Build was failed"

deploy:
  skip_cleanup: true
  provider: script
  script: mvn heroku:deploy -B -Dmaven.test.skip=true -pl backend
  on:
    branch: master