export const GAME_LOAD_CARDS = 'GAME_LOAD_CARDS'
export const GAME_SELECT_CARD = 'GAME_SELECT_CARD'
export const GAME_NEW_CARDS = 'GAME_NEW_CARDS'
export const GAME_CREATE = 'GAME_CREATE'
export const GAME_SET_ROOM = 'GAME_SET_ROOM'
export const GAME_AGENT = 'GAME_AGENT'
export const GAME_CHIEF = 'GAME_CHIEF'
export const GAME_EXIT = 'GAME_EXIT'
