export const ROOMS_LIST_REQUEST = 'ROOMS_LIST_REQUEST'
export const ROOMS_LIST_SUCCESS = 'ROOMS_LIST_SUCCESS'
export const ROOMS_LIST_ERROR = 'ROOMS_LIST_ERROR'
export const ROOMS_LIST_ADD = 'ROOMS_LIST_ADD'

